version: "3"
services:
  flask:
    build: .
    container_name: flask-api
    restart: always
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: flask-api-nginx
    restart: always
    ports:
      - "8083:8080"